version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todolist_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: dockerfile
    container_name: api_container
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      API_PORT: ${API_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - '${API_PORT}:8000'
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  db_data:
