version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todolist_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todolist
      MYSQL_USER: todo
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
